apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
    releaseName: kube-prometheus-stack
    namespace: prometheus
    version: "61.2.0"
    repo: https://prometheus-community.github.io/helm-charts
    apiVersions:
      - autoscaling/v2
      - discovery.k8s.io/v1/EndpointSlice
      - policy/v1
      - policy/v1/PodDisruptionBudget
      - networking.k8s.io/v1
      - rbac.authorization.k8s.io/v1


patches:
  - target:
      kind: ServiceMonitor
    patch: |-
      - op: add
        path: /metadata/labels/prometheus
        value: prometheus-operator
  - target:
      kind: IngressRoute
      name: prometheus-server
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`prometheus.192.168.200.200.nip.io`)
  - target:
      kind: IngressRoute
      name: grafana-server
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`grafana.192.168.200.200.nip.io`)


