apiVersion: v1
kind: ConfigMap
metadata:
  name: toolbox-server
data:
  toolbox: https://toolbox.192.168.200.200.nip.io/
  redirects.yaml: |
    argocd:
      logs: 
      metrics: 
      url: https://argocd.192.168.200.200.nip.io/
      docs: https://argo-cd.readthedocs.io/en/stable/
      repo: https://github.com/argoproj/argo-cd
    traefik:
      logs:
      metrics: 
      url: https://traefik-dashboard.192.168.200.200.nip.io/
      docs: https://doc.traefik.io/traefik/
      repo: https://github.com/traefik/traefik/
    toolbox:
      logs: 
      metrics:
      url: https://toolbox.192.168.200.200.nip.io/
      docs: 
      repo: