apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - ../../base
  - config.yaml

replacements:
  - source:
      kind: ConfigMap
      name: toolbox-server
      fieldPath: data.toolbox
      options:
        delimiter: "/"
        index: 2
        create: false
    targets:
      - select:
          kind: IngressRoute
          name: toolbox-server
        fieldPaths:
          - spec.routes.*.match
        options:
          delimiter: "`"
          index: 1
          create: false
