apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ApplicationSet
      name: (argocd|addons)
    patch: |-
      - op: replace
        path: /spec/generators/0/matrix/generators/0/list/elements
        value: 
          - envName: local
            server: https://kubernetes.default.svc
            argoResourceNameSuffix: ""

            projectAppsBranch: "master"
            projectAppsRepo: ""
            projectAppsAutoSync: "false"
            projectAppsAutoSyncPrune: "true"

            addonsAppsBranch: "master"
            addonsAppsRepo: "git@github.com:siriusopt/infra_k8s_addons.git"
            addonsAppsAutoSync: "true"
            addonsAppsAutoSyncPrune: "true"

            argocdAppsBranch: "master"
            argocdAppsRepo: "git@github.com:siriusopt/infra_k8s_addons.git"
            argocdAppsAutoSync: "false"
            argocdAppsAutoSyncPrune: "true"
