apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources

helmCharts:
  - name: vault
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
    releaseName: vault
    namespace: vault
    version: "0.25.0"
    repo: https://helm.releases.hashicorp.com


patches:
  - target:
      kind: IngressRoute
      name: vault-ui
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`vault.192.168.200.200.nip.io`)


