apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - ../../base

# TODO: kustomize resources, nodeSelector, replicas and scaling
# TODO: move it to helm chart?
