apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: over-provisioning
value: -1
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Priority class for over-provisioning"