apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Priority class for workloads that not require high-availability"