apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal-priority
value: 100
globalDefault: true
preemptionPolicy: PreemptLowerPriority
description: "Default priority for workloads which can be preempted in specific conditions to make space for workloads with the highest priority"