{{- if .Values.networkPolicy.blockAll.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
---
{{- if .Values.networkPolicy.allowClusterDNS.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ include  "addons-defaults.namespace" . }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
{{- end }}