apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: addons-vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret/local"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-addons"
  conditions:
    - namespaces:
        - "argocd"